version: "3.4"

services:
  app:
    ports:
      - "8080:8080"
    volumes:
      - ./.docker-data/app:/app/logs
    networks:
      - network
    build:
      context: "."
      dockerfile: "build/Dockerfile"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 5s

  db-test:
    image: "postgres:9.5"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp_test
    networks:
      - network

networks:
  network: {}
